---
--- Primary Keys: 
---

ALTER TABLE AT010 ADD CONSTRAINT AT010_PK PRIMARY KEY (CDBUMON);
ALTER TABLE AT011 ADD CONSTRAINT AT011_PK PRIMARY KEY (CDBUMON, DTHAKKOUNENGETSU);
ALTER TABLE AT020 ADD CONSTRAINT AT020_PK PRIMARY KEY (NRJYUGYOIN);
ALTER TABLE AT021 ADD CONSTRAINT AT021_PK PRIMARY KEY (NRJYUGYOIN, DTSYOZOKUNENGETSU);
ALTER TABLE ZT010 ADD CONSTRAINT ZT010_PK PRIMARY KEY (IDVARIANT);
ALTER TABLE ZT020 ADD CONSTRAINT ZT020_PK PRIMARY KEY (IDUSER);
ALTER TABLE ZT030 ADD CONSTRAINT ZT030_PK PRIMARY KEY (IDNUMBER);
ALTER TABLE ZT040 ADD CONSTRAINT ZT040_PK PRIMARY KEY (IDUSERKUBUN, KBUSERKUBUN);
ALTER TABLE ZT050 ADD CONSTRAINT ZT050_PK PRIMARY KEY (NRSESSION);
ALTER TABLE ZT051 ADD CONSTRAINT ZT051_PK PRIMARY KEY (NRSESSION, SQPROGRAM);
ALTER TABLE ZT060 ADD CONSTRAINT ZT060_PK PRIMARY KEY (DTSTART);
ALTER TABLE ZT070 ADD CONSTRAINT ZT070_PK PRIMARY KEY (KBCALENDAR, DTOFF);
ALTER TABLE ZT080 ADD CONSTRAINT ZT080_PK PRIMARY KEY (KBCURRENCY, DTNEND);
ALTER TABLE ZT081 ADD CONSTRAINT ZT081_PK PRIMARY KEY (KBCURRENCY, DTNEND, DTMSEQ);

